""" Automatically silence sensitive audio

Uses PySox which is wrapper for the CLT interface with the
SoX audio editing software.

Timing of silences is generated by human annotation
and stored as a JSON file.

Audio files should be stored in a folder named raw_audio
and you should create another directory named processed_audio
for the silenced audio files.
"""

import sox
import os


def silence_audio(file_name, silence_timing, output_dir, db_reduction):
    '''
    Silence audio that contains sensitive information.
    Inputs are the name of file as a string and a dictionary
    of timing information with audio file name as the key.
    Output is a silenced audio file.
    '''
    # check if output dir exists if not create it
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # process the audio
    tfm = sox.Transformer()  # create Transformer object
    tfm.trim(silence_timing[file_name][0], silence_timing[file_name][1])
    tfm.gain(gain_db=-db_reduction)  # silence by reducing decibels
    tfm.build(os.path.join('raw_audio/', file_name),
              os.path.join('processed_audio/', file_name))

    # check whether audio file is silent
    print(sox.file_info.info(os.path.join('processed_audio/',
                                          file_name))['silent'])
